### ISSUE TITLE
L'Académie française est opposée à la réforme

### ISSUE THREAD

**Issue by ericguirbal** [leejo/acme-ognon#3]
Hey,

Attention aux sous-entendus  ; comme vient de le rappeler sa secrétaire perpétuelle, Hélène Carrère d'Encausse, l'Académie française n'a rien à voir avec cette réforme et ne l'approuve pas. Je pense qu'il serait plus juste de remercier Michel Rocard, le Conseil supérieur de la langue française, Najat Vallaud Belkacem...

**Comment by leejo** [comment]
Ah ouai ? D'accord, je changerai le POD. Je dois lire le proposition en full...
